### ISSUE TITLE
Regarding forum link at the readme file

### ISSUE THREAD

**Issue by muhamdasim** [drmagma/i2pchat#95]
Hi there
The link to the forum is not working.
It is request to please update them asap.
Thank You

**Comment by tattwamasii2p** [comment]
Hi @muhamdasim — the forum is down since long ago; the link is thus obsolete. I guess I have forum thread backup somewhere — need to search.

**Comment by tattwamasii2p** [comment]
@muhamdasim I have no backup for the forum thread, sorry. Marked links as obsolete at Readme; closing this issue.

**Comment by tattwamasii2p** [comment]
the chat forum is at irc2p `#saltr`

**Comment by tattwamasii2p** [comment]
and also at irc.ilita.i2p `#i2pchat` and `#i2pchat_official`
